### PR TITLE
Add a build for Swift on Debian 9.5.

### PR DESCRIPTION
**Pull request by Frizlab**

### CODE REVIEW

**Comment by shahmishal** [comment]
Job: https://ci-external.swift.org/job/oss-swift-RA-linux-debian-9_5/
Node: https://ci-external.swift.org/computer/debian-9.5/

**Comment by shahmishal** [comment]
@Frizlab Debian 9.5 node has been offline for a while now, is this expected?
https://ci-external.swift.org/computer/debian-9.5/

**Comment by Frizlab** [comment]
No my server is still up and running, I did not change any conf nor did any particular operation on it apart from regular updates (Debian version is now 9.13).
I tried looking at the logs on the Jenkins but I don’t see anything https://ci-external.swift.org/computer/debian-9.5/log

**Comment by shahmishal** [comment]
We are seeing: (Sorry for late reply)
```
[08/02/21 14:31:08] [SSH] Authentication failed.
Authentication failed.
```

**Pull request merged**
