### PR TITLE
Add aarch64 node

### PR DESCRIPTION
**Pull request by futurejones**
Add node for arm64/aarch64 ubuntu 16.04

### CODE REVIEW

**Comment by vielmetti** [comment]
PR should include an update to the README file too

https://github.com/apple/swift-community-hosted-continuous-integration/blob/master/README.md

**Comment by shahmishal** [comment]
@futurejones Email sent for additional information.

**Comment by vielmetti** [comment]
@shahmishal Happy to also be part of the conversation if you have any questions about @packethost and the Works on Arm program.

**Comment by shahmishal** [comment]
Node: https://ci-external.swift.org/computer/ubuntu-16.04-aarch64/
Jobs:
- swift-4.1-branch - https://ci-external.swift.org/job/oss-swift-4.1-RA-linux-ubuntu-16.04-aarch64/
- swift-4.2-branch - https://ci-external.swift.org/job/oss-swift-4.2-RA-linux-ubuntu-16.04-aarch64/

**Comment by shahmishal** [comment]
@futurejones, are you aware of the current failure? 

```
Foundation/NSString.swift:1182:106: error: cannot convert value of type 'CVaListPointer' to expected argument type 'va_list' (aka '__va_list')
        let str = CFStringCreateWithFormatAndArguments(kCFAllocatorSystemDefault, nil, format._cfObject, argList)!
                                                                                                         ^~~~~~~
Foundation/NSString.swift:1190:148: error: cannot convert value of type 'CVaListPointer' to expected argument type 'va_list' (aka '__va_list')
                str = CFStringCreateWithFormatAndArguments(kCFAllocatorSystemDefault, unsafeBitCast(loc, to: CFDictionary.self), format._cfObject, argList)
                                                                                                                                                   ^~~~~~~
Foundation/NSString.swift:1195:106: error: cannot convert value of type 'CVaListPointer' to expected argument type 'va_list' (aka '__va_list')
            str = CFStringCreateWithFormatAndArguments(kCFAllocatorSystemDefault, nil, format._cfObject, argList)
                                                                                                         ^~~~~~~
Foundation/NSString.swift:1202:100: error: cannot convert value of type 'CVaListPointer' to expected argument type 'va_list' (aka '__va_list')
            CFStringCreateWithFormatAndArguments(kCFAllocatorSystemDefault, nil, format._cfObject, vaPtr)
                                                                                                   ^~~~~
```

https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04-aarch64/4/console
https://ci-external.swift.org/job/oss-swift-4.1-RA-linux-ubuntu-16.04-aarch64/1/console
https://ci-external.swift.org/job/oss-swift-4.2-RA-linux-ubuntu-16.04-aarch64/5/console

**Comment by futurejones** [comment]
Yes I am aware of these issues.
A PR was submitted on Mar 12 to fix this.
https://github.com/apple/swift/pull/15174

**Pull request merged**
