### PR TITLE
ppc64le support.

### PR DESCRIPTION
**Pull request by asowani**
Modified preset to "buildbot_linux" from just "buildbot".

### CODE REVIEW

**Comment by asowani** [comment]
Also, it is desired to run tests hence pulled out "test=no". If it shows many adverse effects, I will re-introduce it.

**Comment by asowani** [comment]
@shahmishal Could you please review these changes? Thanks!

**Comment by shahmishal** [comment]
Build with new change: 
https://ci-external.swift.org/view/swift-4.1-branch/job/oss-swift-4.1-RA-linux-ubuntu-16.04-ppc64le/3/console

**Comment by shahmishal** [comment]
Failed, please make sure utils/build-presets.ini has the preset.  

```
./swift/utils/build-script: fatal error: preset 'buildbot_linux,tools=RA,stdlib=RD' not found
```

**Comment by asowani** [comment]
strange! utils/build-presets.ini file has this entry at line 765:
[preset: buildbot_linux,no_test]

Looking into the issue...

**Pull request merged**
