### PR TITLE
Add a build for Swift for TensorFlow on MacOS High Sierra

### PR DESCRIPTION
**Pull request by m3bm3b**
This is a MacOS build for Swift for TensorFlow, much like the existing
Swift for TensorFlow build for Ubuntu 16.04.

### CODE REVIEW

**Comment by shahmishal** [comment]
@m3bm3b @rxwei Email sent for additional information.

**Comment by rxwei** [comment]
Sent a response.

**Comment by shahmishal** [comment]
Please install cmake on the node host. 

```
./swift/utils/build-script: note: Using toolchain default
./swift/utils/build-script: fatal error: can't find CMake (please install CMake)
./swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
```

**Comment by shahmishal** [comment]
Job: https://ci-external.swift.org/job/oss-swift-RA-macOS-tensorflow/
Node: https://ci-external.swift.org/computer/macOS-tensorflow/

**Comment by m3bm3b** [comment]
> Please install cmake on the node host.

How odd.

For me (as user swiftci):
  pro37-vm-1:~ swiftci$ which cmake
  /usr/local/bin/cmake
  pro37-vm-1:~ swiftci$ cmake --version
  cmake version 3.9.5

  CMake suite maintained and supported by Kitware (kitware.com/cmake).
  pro37-vm-1:~ swiftci$

And when I try to build everything works as expected.
Presumably jenkins expects to use a particular $PATH.
I'll try installing cmake in a different way.

Mike

**Comment by shahmishal** [comment]
Thanks!

**Pull request merged**
