### PR TITLE
Ubuntu 16.04 x86_64

### PR DESCRIPTION
**Pull request by fiveze**
Platform: x86_64
OS version: Ubuntu 16.04
Branch: master
Preset: buildbot_linux_1604

### CODE REVIEW

**Comment by shahmishal** [comment]
@fiveze Email sent for additional information.

**Comment by shahmishal** [comment]
Can you also update "Current List of Platforms" in the README?

**Comment by fiveze** [comment]
@shahmishal done. I've also specified Ubuntu version.

**Comment by shahmishal** [comment]
Job - https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-16.04/
Node - https://ci-external.swift.org/computer/ubuntu-16.04/

Thanks @fiveze!

**Comment by shahmishal** [comment]
@fiveze, Have you seen this issue? 
https://bugs.swift.org/browse/SR-7688

**Comment by shahmishal** [comment]
This node is offline - https://ci-external.swift.org/computer/ubuntu-16.04/

**Pull request merged**
